Repository oss-aspen/8Knot, pull requests merged in 2025-08, with the labels that each got.

#908 Simplify Dockerfile builds (actually install to system) and fix hot reload
  docker-compose.yml
  docker/Dockerfile
Labels: devops

#920 Collapsible sidebar
  8Knot/pages/index/index_callbacks.py
  8Knot/pages/index/index_layout.py
Labels: enhancement

#930 Bring dash dependency fully up to date
  pyproject.toml
  uv.lock
Labels: dependencies
